question: "Install Telegram Desktop?"
steps:
  - Installing dependencies:
    - sudo apt update
    - sudo apt install wget

  - Downloading Telegram Desktop:
    - wget -O /tmp/telegram.tar.xz https://telegram.org/dl/desktop/linux

  - Unpacking Telegram Desktop:
    - tar xf /tmp/telegram.tar.xz -C /home/$(whoami)/.local/share/

  - Add symlink to telegram-desktop:
    - ln -s /home/$(whoami)/.local/share/Telegram/Telegram /home/$(whoami)/.local/share/Telegram/telegram-desktop

  - Add Telegram Desktop to PATH:
    - echo echo "PATH=/home/$(whoami)/.local/share/Telegram:\$PATH" >> /home/$(whoami)/.bashrc && . /home/$(whoami)/.bashrc
    - if [ -f "/home/$(whoami)/.config/fish/config.fish" ];
        then echo "fish_add_path /home/$(whoami)/.local/share/Telegram" >> /home/$(whoami)/.config/fish/config.fish;
      fi

  - Test launch Telegram Desktop in tray:
    - (/home/$(whoami)/.local/share/Telegram/telegram-desktop -startintray &) && sleep 2 && killall telegram-desktop

  - Cleanup downloaded files:
    rm -f /tmp/telegram.tar.xz
